# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: ["master"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # - name: Switch branch
      #   run: |
      #     git checkout gh-pages

      - name: ssh deploy
        # You may pin to the exact commit or the version.
        # uses: easingthemes/ssh-deploy@3884c8554ff45c0fd37d3f12a76288d06ce7a2ff
        uses: easingthemes/ssh-deploy@v4.1.8
        with:
          # Private key part of an SSH key pair
          SSH_PRIVATE_KEY: ${{ secrets.SSH_KEY }}
          # Remote host
          REMOTE_HOST: ${{ secrets.SSH_HOST }}
          # Remote user
          REMOTE_USER: ${{ secrets.SSH_USER }}
          # Remote port
          REMOTE_PORT: ${{ secrets.SSH_PORT }} # optional, default is 22
          # Source directory, path relative to `$GITHUB_WORKSPACE` root, eg: `dist/`
          SOURCE: ".deploy_git/" # optional, default is
          # Target directory
          TARGET: ${{ secrets.SSH_TARGET }} # optional, default is
          # Arguments to pass to rsync
          # ARGS: "-avzr --delete" # optional, default is -rlgoDzvc -i
          # An array of ssh arguments, they must be prefixed with -o and separated by a comma, for example: -o SomeArgument=no, -o SomeOtherArgument=5
